theme: jekyll-theme-minimal
title: ViaCEP Rust client
description: The ViaCEP client for Rust projects.
logo: https://raw.githubusercontent.com/guibranco/viacep-rust/main/logo.png
show_downloads: true
