os:
  - Visual Studio 2022

environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
      BITS: 32
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64
    - TARGET: i686-pc-windows-msvc
      BITS: 32
    - TARGET: x86_64-pc-windows-msvc
      BITS: 64

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-toolchain=stable-%TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build

deploy:

- provider: GitHub
  on:
   branch: main
  tag: v$(appveyor_build_version)
  description: Release v$(appveyor_build_version)
  auth_token: $(GITHUB_TOKEN)
  force_update: true
